#!/bin/bash
# /etc/init.d/camservice

### BEGIN INIT INFO
### END INIT INFO


case "$1" in 
    start)
        echo "Starting camservice"
        sudo nohup ./home/pi/corcovadoStream/autoCam.sh &
        ;;
    stop)
        echo "Stopping camservice"
        killall autoCam.sh
        ;;
    *)
        echo "Usage: /etc/init.d/camservice start|stop"
        exit 1
        ;;
esac

exit 0